name: Button-Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_button:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Button Component Tests
      run: npm run test __test__/Button.test.js
 
      id: test_button_output
      continue-on-error: true

    - name: Set Test Result
      if: always()
      run: echo "::set-output name=button_tests_result::${{ job.status }}"
    
    - name: Final Message
      if: success()
      run: echo "Button component tests passed! ğŸ‰"
    
    - name: Final Message on Failure
      if: failure()
      run: echo "Button component tests failed! âŒ"